@startuml GameEngineSandbox
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(player, "Player")

System_Boundary(game, "Flappy Bird") {
    System(flappyBird, "flappyBird")
}

System_Boundary(engine, "Game Engine") {
    System(application, "engine")
    System(audio, "audio")
    System(filesystem, "filesystem")
    System(game-loop, "game-loop")
    System(http, "http")
    System(input, "input")
    System(physics, "physics")
    System(renderers, "renderers")
    System(resources, "resources")
    System(scenes, "scenes")
    System(utilities, "utilities")
}

System_Boundary(thirdparty, "Thirdparty") {
    System(angle, "angle")
    System(cpr, "cpr")
    System(entt, "entt")
    System(glm, "glm")
    System(openal-soft, "openal-soft")
    System(tweeny, "tweeny")
    System(vcpkg, "vcpkg")
}

Rel(player, flappyBird, Plays)

Rel(flappyBird, application, Uses)
Rel(flappyBird, game-loop, Uses)
Rel(flappyBird, renderers, Uses)
Rel(flappyBird, textures, Uses)
Rel(flappyBird, input, Uses)
Rel(flappyBird, scenes, Uses)
Rel(flappyBird, physics, Uses)
Rel(flappyBird, tweeny, Uses)

Rel(application, game-loop, Uses)
Rel(application, utilities, Uses)

Rel(audio, utilities, Uses)
Rel(audio, resources, Uses)

Rel(filesystem, utilities, Uses)

Rel(game-loop, utilities, Uses)
Rel(game-loop, scenes, Uses)
Rel(game-loop, input, Uses)
Rel(game-loop, resources, Uses)
Rel(game-loop, renderers, Uses)

Rel(http, utilities, Uses)

Rel(input, utilities, Uses)

Rel(physics, utilities, Uses)

Rel(renderers, utilities, Uses)
Rel(renderers, filesystem, Uses)
Rel(renderers, resources, Uses)
Rel(renderers, glm, Uses)

Rel(resources, utilities, Uses)
Rel(resources, filesystem, Uses)
Rel(resources, glm, Uses)

Rel(scenes, renderers, Uses)
Rel(scenes, utilities, Uses)

@enduml