@startuml GameEngineSandbox
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Person(player, "Player")

System_Boundary(game, "Flappy Bird") {
    System(flappyBird, "flappyBird")
}

System_Boundary(engine, "Game Engine") {
    System(application, "engine")
    System(audio, "audio")
    System(filesystem, "filesystem")
    System(gameLoop, "game-loop")
    System(http, "http")
    System(input, "input")
    System(physics, "physics")
    System(renderers, "renderers")
    System(resources, "resources")
    System(scenes, "scenes")
    System(utilities, "utilities")
}

System_Boundary(thirdparty, "Thirdparty") {
    System(angle, "angle")
    System(cpr, "cpr")
    System(entt, "entt")
    System(glfw, "glfw")
    System(glm, "glm")
    System(openalSoft, "openal-soft")
    System(tweeny, "tweeny")
    System(vcpkg, "vcpkg")
}

Rel(player, flappyBird, Plays)

Rel(flappyBird, application, Uses)
Rel(flappyBird, gameLoop, Uses)
Rel(flappyBird, renderers, Uses)
Rel(flappyBird, input, Uses)
Rel(flappyBird, scenes, Uses)
Rel(flappyBird, physics, Uses)
Rel(flappyBird, tweeny, Uses)

Rel(application, gameLoop, Uses)
Rel(application, utilities, Uses)

Rel(audio, utilities, Uses)
Rel(audio, resources, Uses)

Rel(filesystem, utilities, Uses)

Rel(gameLoop, utilities, Uses)
Rel(gameLoop, scenes, Uses)
Rel(gameLoop, input, Uses)
Rel(gameLoop, resources, Uses)
Rel(gameLoop, renderer, Uses)

Rel(physics, utilities, Uses)

Rel(renderer, utilities, Uses)
Rel(renderer, filesystem, Uses)
Rel(renderer, resources, Uses)
Rel(renderer, glm, Uses)

Rel(resources, utilities, Uses)
Rel(resources, filesystem, Uses)

@enduml
